# AWS Organization Account Configuration
# Update with your actual account IDs and role names

accounts:
  dev:
    account_id: "111111111111"              # Replace with actual dev account ID
    role_name: "OrganizationAccountAccessRole"
    region: "us-east-1"
    environment: "development"
    backend_bucket: "terraform-state-dev-111111111111"
    backend_key: "iam-management/terraform.tfstate"
    backend_region: "us-east-1"
    backend_dynamodb_table: "terraform-locks-dev"
    
  qa:
    account_id: "222222222222"              # Replace with actual QA account ID  
    role_name: "OrganizationAccountAccessRole"
    region: "us-east-1"
    environment: "qa"
    backend_bucket: "terraform-state-qa-222222222222"
    backend_key: "iam-management/terraform.tfstate"
    backend_region: "us-east-1"
    backend_dynamodb_table: "terraform-locks-qa"
    
  test:
    account_id: "333333333333"              # Replace with actual test account ID
    role_name: "OrganizationAccountAccessRole"
    region: "us-west-2"                     # Different region for test
    environment: "test"
    backend_bucket: "terraform-state-test-333333333333"
    backend_key: "iam-management/terraform.tfstate"
    backend_region: "us-west-2"
    backend_dynamodb_table: "terraform-locks-test"
    
  prod:
    account_id: "444444444444"              # Replace with actual prod account ID
    role_name: "OrganizationAccountAccessRole"
    region: "us-east-1"
    environment: "production"
    backend_bucket: "terraform-state-prod-444444444444"
    backend_key: "iam-management/terraform.tfstate"
    backend_region: "us-east-1"
    backend_dynamodb_table: "terraform-locks-prod"

# Global settings
organization:
  master_account_id: "000000000000"        # Replace with your organization master account
  role_session_name: "TerraformAssumeRole"
  max_session_duration: 3600               # 1 hour
  external_id: ""                          # Optional: set if using external ID

# Default tags applied to all resources
default_tags:
  ManagedBy: "Terraform"
  Project: "IAM-Management"
  Owner: "Platform-Team"
  
# Environment-specific settings
environment_settings:
  dev:
    allowed_regions: ["us-east-1", "us-west-2"]
    policy_prefix: "dev-"
    role_prefix: "dev-"
    
  qa:
    allowed_regions: ["us-east-1"]
    policy_prefix: "qa-"
    role_prefix: "qa-"
    
  test:
    allowed_regions: ["us-west-2"]
    policy_prefix: "test-"
    role_prefix: "test-"
    
  prod:
    allowed_regions: ["us-east-1", "us-west-2"]
    policy_prefix: "prod-"
    role_prefix: "prod-"
    require_mfa: true                       # Production requires MFA